apiVersion: 1
datasources:
  - name: prometheus-container
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus-container
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: 60s