{
 "title": "Global_dashboard",
 "description": "Global apps dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, app)"
    }
   },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": {
     "query": "label_values(up{app=\"$app\",namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app=\"$app\", pod=~\"$pod_name\", area=\"heap\",namespace=\"$namespace\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{app=\"$app\", pod=~\"$pod_name\", area=\"nonheap\",namespace=\"$namespace\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top RPS (by URI)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk (5, sum by (app, method, uri) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", uri!~\".*prometheus.*|.*healthcheck.*|root|/\\\\{name\\\\}/\\\\{profiles.*\"}[$__rate_interval])))",
     "legendFormat": "{{app}} [{{method}}] {{uri}}"
    }
   ]
  },
  {
   "title": "Top RPS (by POD)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk (5, sum by (pod) (irate(http_server_requests_seconds_count{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttled",
   "type": "timeseries",
   "description": "Reports the number of times that the CPU usage has reached the value set in limits",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod)(irate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\"}[$__rate_interval]) > 0.5)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deploy status",
   "type": "timeseries",
   "description": "Deployments = Replica missmatch  \nStatefulsets = Replica missmatch  \nDaemonsets = Replica missmatch ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{phase!=\"Running\", phase!=\"Succeeded\", namespace=~\"$namespace\"})",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(kube_replicaset_spec_replicas{namespace=~\"$namespace\"}) - sum(kube_replicaset_status_ready_replicas{namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})",
     "legendFormat": "Jobs"
    },
    {
     "expr": "sum(changes(kube_pod_status_ready{namespace=~\"$namespace\", condition=\"true\"}[$__rate_interval]))",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum(kube_statefulset_replicas{namespace=~\"$namespace\"}) - sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_status_number_misscheduled{namespace=~\"$namespace\"})",
     "legendFormat": "Daemonsets"
    }
   ]
  },
  {
   "title": "Memory Limit Rate",
   "type": "timeseries",
   "description": "Reports the number of times that the memory usage has reached the value set in limits",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_failcnt{namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval]) != 0)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Top Error & Warn Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "topk (5, sum by (app, level) (irate(logback_events_total{namespace=\"$namespace\", level=~\"warn|error\"}[$__rate_interval]) != 0))",
     "legendFormat": "{{app}} - {{level}}"
    }
   ]
  },
  {
   "title": "Top Average Latency (by URI)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk (5, sum by(app, method, uri) (increase(http_server_requests_seconds_sum{namespace=\"$namespace\", uri!~\".*prometheus.*|.*healthcheck.*|root|/\\\\{name\\\\}/\\\\{profiles.*\"}[$__rate_interval]))\n/\n(sum by(app, method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", uri!~\".*prometheus.*|.*healthcheck.*|root|/\\\\{name\\\\}/\\\\{profiles.*\"}[$__rate_interval])) != 0))",
     "legendFormat": "{{app}} [{{method}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_server_requests_seconds_count{namespace=\"$namespace\", uri!~\".*prometheus.*|.*healthcheck.*|root|/\\\\{name\\\\}/\\\\{profiles.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$pod_name\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Namespace CPU Cores Quota ($namespace)",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.cpu\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.cpu\"})"
    },
    {
     "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.cpu\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.cpu\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.cpu\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.cpu\"})"
    },
    {
     "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.cpu\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.cpu\"})"
    }
   ]
  },
  {
   "title": "Namespace Memory Quota ($namespace)",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.memory\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.memory\"})"
    },
    {
     "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"requests.memory\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"requests.memory\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.memory\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.memory\"})"
    },
    {
     "expr": "100\n/\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"hard\", resource=\"limits.memory\"})\n*\nsum by (namespace) (kube_resourcequota{namespace=~\"$namespace\", type=\"used\", resource=\"limits.memory\"})"
    }
   ]
  },
  {
   "title": "Deploy Availability / Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Starts",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by (pod) (changes(kube_pod_status_ready{namespace=~\"$namespace\", condition=\"true\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods in Status Phase = Failed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_status_phase{phase!=\"Running\", phase=\"Failed\", namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods in Status Phase = Pending",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_status_phase{phase!=\"Running\", phase=\"Pending\", namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods in Status Phase = Unknown",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum by (pod) (kube_pod_status_phase{phase!=\"Running\", phase=\"Unknown\", namespace=~\"$namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Deployments/Replicasets with Replica missmatch",
     "type": "timeseries",
     "description": "No data means there are no Deployments in this namespace",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum by (replicaset) (kube_replicaset_spec_replicas{namespace=~\"$namespace\"})\n-\nsum by (replicaset) (kube_replicaset_status_ready_replicas{namespace=~\"$namespace\"})\nand\nsum by (replicaset) (kube_replicaset_spec_replicas{namespace=~\"$namespace\"}) > 0",
       "legendFormat": "{{replicaset}}"
      }
     ]
    },
    {
     "title": "Statefulsets with Replica missmatch",
     "type": "timeseries",
     "description": "No data means there are no Statefulsets in this namespace",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "sum by (statefulset) (kube_statefulset_replicas{namespace=~\"$namespace\"}) - sum by (statefulset) (kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})",
       "legendFormat": "{{statefulset}}"
      }
     ]
    },
    {
     "title": "Failed Jobs",
     "type": "timeseries",
     "description": "No data means there are no Jobs/CronJobs in this namespace",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum by (job_name) (kube_job_status_failed{namespace=~\"$namespace\"})",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Daemonsets misscheduled",
     "type": "timeseries",
     "description": "No data means there are no Daemonsets in this namespace",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "sum by (daemonset) (kube_daemonset_status_number_misscheduled{namespace=~\"$namespace\"})",
       "legendFormat": "{{daemonset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod, httpStatusCode, routeId) (irate(spring_cloud_gateway_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*|root|/\\\\{name\\\\}/\\\\{profiles.*\"}[$__rate_interval]))",
       "legendFormat": "[{{httpStatusCode}}] {{routeId}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod, httpStatusCode, routeId) (increase(spring_cloud_gateway_requests_seconds_sum{namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*|root|/\\\\{name\\\\}/\\\\{profiles.*\"}[$__rate_interval]))\n/\n(sum by(pod, httpStatusCode,routeId) (increase(spring_cloud_gateway_requests_seconds_count{namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*|root|/\\\\{name\\\\}/\\\\{profiles.*\"}[$__rate_interval])) != 0)",
       "legendFormat": "[{{httpStatusCode}}] {{routeId}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Max Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, httpStatusCode, routeId) (spring_cloud_gateway_requests_seconds_max{namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*\"})",
       "legendFormat": "[{{httpStatusCode}}] {{routeId}} - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (pod)(jvm_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"heap\"})*100/avg by (pod)(jvm_memory_max_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"heap\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Log Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (level) (irate(logback_events_total{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval]))",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}*1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (pod)(jvm_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"nonheap\"})*100/avg by (pod)(jvm_memory_max_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"nonheap\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod, method, uri) (irate(http_server_requests_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*\"}[$__rate_interval]))",
       "legendFormat": "{{method}} - {{uri}} [{{pod}}]"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod, method, uri) (increase(http_server_requests_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\"/api/prometheus|/api/healthcheck\"}[$__rate_interval]))\n / \n(sum by(pod, method, uri) (increase(http_server_requests_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\"/api/prometheus|/api/healthcheck\"}[$__rate_interval]) !=0))",
       "legendFormat": "{{method}} - {{uri}} [{{pod}}]"
      }
     ]
    },
    {
     "title": "Max Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, method, uri) (http_server_requests_seconds_max{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*\"})",
       "legendFormat": "{{method}} - {{uri}} [{{pod}}]"
      }
     ]
    },
    {
     "title": "95 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\"/api/prometheus|/api/healthcheck\"}[$__rate_interval])) by(pod, method, uri, le))",
       "legendFormat": "{{method}} - {{uri}} [{{pod}}]"
      }
     ]
    },
    {
     "title": "99 Percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\"/api/prometheus|/api/healthcheck\"}[$__rate_interval])) by(pod, method, uri, le))",
       "legendFormat": "{{method}} - {{uri}} [{{pod}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Client Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod, method, clientName, uri) (irate(http_client_requests_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*\"}[$__rate_interval]))",
       "legendFormat": "{{clientName}} {{method}} {{uri}} [{{pod}}]"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(pod, clientName, method, uri) (increase(http_client_requests_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\"/api/prometheus|/api/healthcheck\"}[$__rate_interval]))\n / \n(sum by(pod, clientName, method, uri) (increase(http_client_requests_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\"/api/prometheus|/api/healthcheck\"}[$__rate_interval])))",
       "legendFormat": "{{clientName}} {{method}} {{uri}} [{{pod}}]"
      }
     ]
    },
    {
     "title": "Max Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, clientName, method, uri) (http_client_requests_seconds_max{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", uri!~\".*prometheus.*|.*healthcheck.*\"})",
       "legendFormat": "{{clientName}} {{method}} {{uri}} [{{pod}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Server Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod, method, result) (irate(grpc_server_calls_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval]))",
       "legendFormat": "{{method}} [{{result}}] - {{pod}}"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod, method, result) (increase(grpc_server_calls_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval])) / sum by (pod, method, result) (increase(grpc_server_calls_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval]) != 0)",
       "legendFormat": "{{method}} [{{result}}] - {{pod}}"
      }
     ]
    },
    {
     "title": "Max Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, method, result) (grpc_server_calls_seconds_max{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{method}} [{{result}}] - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Client Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (pod, service, method, statusCode) (irate(grpc_client_processing_duration_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval]))",
       "legendFormat": "{{service}} {{method}} [{{statusCode}}] - {{pod}}"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod, service, method, statusCode) (increase(grpc_client_processing_duration_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval])) \n/ \nsum by (pod, service, method, statusCode) (increase(grpc_client_processing_duration_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval]))",
       "legendFormat": "{{service}} {{method}} [{{statusCode}}] - {{pod}}"
      }
     ]
    },
    {
     "title": "Max Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (pod, service, method, statusCode) (grpc_client_processing_duration_seconds_max{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{service}} {{method}} [{{statusCode}}] - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pool) (hikaricp_connections{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (pool) (hikaricp_connections_timeout_total{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Connections Active",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod, pool) (hikaricp_connections_active{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{pool}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Connections Pending",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod, pool) (hikaricp_connections_pending{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{pool}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Connections Idle",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pool, pod) (hikaricp_connections_idle{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{pool}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Connection Creation Time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod, pool) (hikaricp_connections_creation_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}) / sum by (pod, pool) (hikaricp_connections_creation_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{pool}} {{pod}}"
      }
     ]
    },
    {
     "title": "Connection Usage Time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod, pool) (hikaricp_connections_usage_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}) / sum by (pod, pool) (hikaricp_connections_usage_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "{{pool}} {{pod}}"
      }
     ]
    },
    {
     "title": "Connection Acquire Time (avg)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod, pool) (hikaricp_connections_acquire_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}) / sum by (pod, pool) (hikaricp_connections_acquire_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "Acquire Time {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumed RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "{{topic}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Commit latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_latency_avg{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "AVG {{pod}} [{{client_id}}]"
      },
      {
       "expr": "kafka_consumer_coordinator_commit_latency_max{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "MAX {{pod}} [{{client_id}}]"
      }
     ]
    },
    {
     "title": "Coordinator stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_rate{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "commit rate - {{pod}} [{{client_id}}]"
      },
      {
       "expr": "kafka_consumer_coordinator_join_rate{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "join rate - {{pod}} [{{client_id}}]"
      },
      {
       "expr": "kafka_consumer_coordinator_heartbeat_rate{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "heartbeat rate - {{pod}} [{{client_id}}]"
      },
      {
       "expr": "kafka_consumer_coordinator_sync_rate{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "sync rate - {{pod}} [{{client_id}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka producer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_producer_record_send_rate{namespace=\"$namespace\", app=~\"$app\"}",
       "legendFormat": "{{pod}} [{{client_id}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (jvm_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "used {{pod}}"
      },
      {
       "expr": "sum by (pod) (jvm_memory_committed_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "committed {{pod}}"
      },
      {
       "expr": "sum by (pod) (jvm_memory_max_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"})",
       "legendFormat": "max {{pod}}"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (jvm_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"heap\"})",
       "legendFormat": "used {{pod}}"
      },
      {
       "expr": "sum by (pod) (jvm_memory_committed_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"heap\"})",
       "legendFormat": "committed {{pod}}"
      },
      {
       "expr": "sum by (pod) (jvm_memory_max_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"heap\"})",
       "legendFormat": "max {{pod}}"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (jvm_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"nonheap\"})",
       "legendFormat": "used {{pod}}"
      },
      {
       "expr": "sum by (pod) (jvm_memory_committed_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"nonheap\"})",
       "legendFormat": "committed {{pod}}"
      },
      {
       "expr": "sum by (pod) (jvm_memory_max_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", area=\"nonheap\"})",
       "legendFormat": "max {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "system - {{pod}}"
      },
      {
       "expr": "process_cpu_usage{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "process - {{pod}}"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[1h])",
       "legendFormat": "process-1h - {{pod}}"
      }
     ]
    },
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "system-1m - {{pod}}"
      },
      {
       "expr": "system_cpu_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "cpu - {{pod}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"} or jvm_threads_live_threads{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "live - {{pod}}"
      },
      {
       "expr": "jvm_threads_daemon{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"} or jvm_threads_daemon_threads{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "daemon - {{pod}}"
      },
      {
       "expr": "jvm_threads_peak{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"} or jvm_threads_peak_threads{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "peak - {{pod}}"
      },
      {
       "expr": "process_threads{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "process - {{pod}}"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "{{state}} - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used {{pod}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited {{pod}}"
      },
      {
       "expr": "jvm_memory_max_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used {{pod}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited {{pod}}"
      },
      {
       "expr": "jvm_memory_max_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval])",
       "legendFormat": "{{action}} ({{cause}}) {{pod}}"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "avg {{action}} ({{cause}}) {{pod}}"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}",
       "legendFormat": "max {{action}} ({{cause}}) {{pod}}"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval])",
       "legendFormat": "allocated {{pod}}"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\"}[$__rate_interval])",
       "legendFormat": "promoted {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"direct\"}",
       "legendFormat": "used {{pod}}"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"direct\"}",
       "legendFormat": "capacity {{pod}}"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"direct\"} or jvm_buffer_count_buffers{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"direct\"}",
       "legendFormat": "count {{pod}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"mapped\"}",
       "legendFormat": "used {{pod}}"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"mapped\"}",
       "legendFormat": "capacity {{pod}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_count{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"mapped\"} or jvm_buffer_count_buffers{app=\"$app\", namespace=\"$namespace\", pod=~\"$pod_name\", id=\"mapped\"}",
       "legendFormat": "count {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}