# Binding From Environment Variables https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables

spring:
  main:
    banner-mode: off
  application:
    name: admin-config-service


server:
  # 0 = random for local dev
  port: 0
management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  health:
    defaults:
      # better create custom HealthIndicator's
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: never
    prometheus:
      enabled: true
    loggers:
      # for boot-admin
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, loggers, openapi, swagger-ui
      base-path: /service
      path-mapping:
        health: healthcheck
    # fot security
    enabled-by-default: false
  server:
    # 0 = random for local dev
    port: 0
  info:
    git:
      enabled: true
    java:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: false
  use-management-port: true

# traceID and spanId are predefined MDC keys - we want the logs to include them
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"