###
// @no-log
// @no-cookie-jar
POST http://localhost:65324/login
Content-Type: application/x-www-form-urlencoded

username=user1&password=1234

###
// @no-log
// @no-cookie-jar
POST http://localhost:65496/accounts/7d02b896-d8ce-4162-99bd-68a772b25409/roles/change
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsInJvbGVzIjoiQURNSU4iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJ1c2VyMSIsIm5iZiI6MTY5MTkzOTc4NSwiZXhwIjoxNjkyMDI2MTg1fQ.mtLJaIgpOIV-C1YlC_r-AcfNVqAVBxlIDxsPsM7XFbP4ToI32I_ks_1Gxu5zntT59YvPgCJaejWhsPkjx4LZyW5KH-BRDhm7IhZBQohFKz4eVbsyLnlo9HNsc4qTrSJZo_9tt9IZQPijY6sMDQ0TM7e53nx7j2tALo580Ow0R_UCPn6QL5W-74V3EaH45Fxu5W1khPVThttYnrlC0-KkvAzDAvoIrrzKv40oER1mRiLeV6lY76q1_HCo8zlWojiAGXJfQbgWlC98HqU6EIs7WdVDto35FRJ2mOK8oICkvO1c_eeB2EkO145Ox5qCv1l5iHCe13JjOIdX46zn4z92dA
Content-Type: application/json

"ADMIN"

###
// @no-log
// @no-cookie-jar
POST http://localhost:65496/accounts/register
Content-Type: application/json

{
  "username": "test2",
  "password": "1234"
}